# Generated by Django 5.1.7 on 2025-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedinmessage',
            options={'ordering': ['-last_message_date']},
        ),
        migrations.RemoveField(
            model_name='linkedinmessage',
            name='sent_date',
        ),
        migrations.RemoveField(
            model_name='linkedinprofile',
            name='url',
        ),
        migrations.AddField(
            model_name='linkedinmessage',
            name='last_message_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
