# Generated by Django 5.1.7 on 2025-03-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizing', '0002_alter_linkedinmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinmessage',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
